#!/bin/python3

import sys
import math


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    lst = []
    for i in range(1, n//2+1):
        a = i
        c = (2*a*a+n*n-2*a*n)//(2*n-2*a)
        b = n-a-c
        if(a > 0 and b > 0 and c > 0):
            if (a*a+b*b==(c*c)):
                if(len(lst)==0 or a*b*c > lst[-1]):
                    lst.append(a*b*c)
    if (len(lst)==0):
        print(-1)
    else:
        print(lst[-1])
