#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    sums = 0
    for i in range(1, n+1):
        sums += i*i
    number = ((n+1)*n)/2
    sums = number*number - sums
    
    print(int(sums))
        
