#!/bin/python3

import sys
import math

t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    yes = True
    while(n%2==0):
        n=n/2
        if(n==1):
            print(n)
            yes = False
            break
    if(yes):
        i = 3
        while (i < math.sqrt(n)+1):
            if(n%i==0):
                n=n/i
            else:
                i+=2
        print(int(n))
