#!/bin/python3

import sys
import math


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    lst = [2,3]
    product = 1
    for i in range(1, int(math.sqrt(n))):
        lst.append(6*i-1)
        lst.append(6*i+1)
    for i in lst:
        if(i <= n):
            temp = 1
            while(temp <= n):
                temp*=i
            product *=temp
            product /=i
    print(int(product))
